services:
  obsv-prometheus:
    image: prom/prometheus:latest
    container_name: obsv-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - elk

  obsv-grafana:
    image: grafana/grafana:latest
    container_name: obsv-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - elk
    depends_on:
      - obsv-prometheus

volumes:
  grafana_data:
