services:
  processing-normalizer-gtfsrt:
    build:
      context: ../../services/normalizer-gtfsrt
    container_name: normalizer-gtfsrt
    env_file:
      - ../../services/normalizer-gtfsrt/.env
    depends_on:
      - stream-kafka
    networks:
      - elk
    restart: unless-stopped
