input {
  kafka {
    bootstrap_servers => "kafka:19092"
    topics => ["normalized.stm.gtfsrt.vehicle_positions.v1"]
    group_id => "logstash_bus_consumer"
    auto_offset_reset => "earliest"
    codec => json
  }
}

filter {
  ruby {
    code => '
      event.set("bus_id", event.get("[payload][vehicle][id]"))
      event.set("type", "bus")
      event.set("[location][lat]", event.get("[payload][position][latitude]"))
      event.set("[location][lon]", event.get("[payload][position][longitude]"))
      event.set("timestamp", event.get("[payload][timestamp]"))
      event.set("occupancy_status", event.get("[payload][occupancy_status]"))
      event.set("route_id", event.get("[payload][trip][route_id]"))
      event.set("trip_id", event.get("[payload][trip][trip_id]"))
      event.set("stop_id", event.get("[payload][stop_id]"))
      event.set("current_status", event.get("[payload][current_status]"))
      event.set("current_stop_sequence", event.get("[payload][current_stop_sequence]"))
      event.set("entity_id", event.get("entity_id"))
      event.set("entity_type", event.get("entity_type"))
      event.set("schema_version", event.get("schema_version"))
    '
  }
}

output {
  if [type] == "bus" {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      index => "bus"
      document_id => "%{[bus_id]}"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    }
  } else {
    elasticsearch {
      hosts => ["https://elasticsearch:9200"]
      index => "default_topic"
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      ssl_enabled => true
      ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    }
  }

  stdout { codec => rubydebug }
}
